# vim: et
---

__monitoring_required_facts:
  - os_family

# This is the set of monitoring packages common across all supported platforms
# Any packages that are specific to a platform should be defined in a
# platform-specific vars file
monitoring_packages:
  - btop
  - ethtool
  - htop
  - iotop
  - iperf3
  - lnav # Log navigator
  - ncdu
  - nmap
  - nethogs
  - net-tools
  - powertop
  - sysstat
  - s-tui
