# vim: et
---

- name: Include platform-specific variables
  ansible.builtin.include_tasks: include_platform_specific_vars.yml

- name: Enable COPR Repos (Fedora)
  ansible.builtin.import_tasks: enable_twm_copr_repos.yml
  when: ansible_facts['os_family'] in ['RedHat', 'Nobara']

- name: Install twm packages
  become: true
  become_user: root
  ansible.builtin.import_tasks: install_twm_packages.yml
  tags:
    - install_packages
    - twm
    - wayland

- name: Set twm dependencies
  # become: true
  # become_user: root
  ansible.builtin.import_tasks: set_wm_service_dependencies.yml

- name: Use default applications
  ansible.builtin.import_tasks: use_default_applications.yml

- name: Set cursor theme
  ansible.builtin.import_tasks: set_cursor_theme.yml
