# vim: et
---

__desktop_required_facts:
  - os_family

desktop_packages:
  - discord
  - krdc # Remote desktop application
  - pinta # From AUR
  - picard
  - putty
  - qbittorrent
  - strawberry
  - vlc
  - yakuake
  - yt-dlp
