# vim: et
---

desktop_packages_common:
  - discord
  - pinta # From AUR
  - picard
  - putty
  - qbittorrent
  - strawberry
  - vlc
  - yakuake
  - yt-dlp

desktop_packages_archlinux:
  - bitwarden
  - kdeconnect
  - obsidian
  - onlyoffice-desktopeditors
  - signal-desktop
  - sweethome3d
  - ttf-fira-code
  - veracrypt

desktop_packages_redhat:
  - fira-code-fonts
  - kde-connect
