# vim: et
---

__twm_required_facts:
  - os_family

# List of packages to install for a workstation with standalone WM
twm_packages:
  - darkman # Dark/light settings
  - fuzzel # Application launcher
  - niri # Scrolling window manager
  - swayidle # Idle manager
  - swaylock # Lock screen manager
  - wev # Debug wayland events
  - xwayland-satellite # X application bridge
