# vim: et
---

twm_packages_platform_specific:
  # Dark material shell, from AUR
  - dms-shell-bin
  # Optional depenency of darkman to determine the location
  - geoclue
  # To do screen sharing
  - wlroots0.18
