# vim: et
---

- name: Install packages (gaming)
  become: true
  ansible.builtin.package:
    name:
      - aisleriot
      - goverlay
      - kmines
      - lutris
      - mangohud
      - steam
    state: present
