# vim: et
---

powerline_shell_theme_file: /usr/lib/python3.13/site-packages/powerline/config_files/themes/shell/__main__.json

common_packages_platform_specific:
  - gvim # provides CLI vim as well
  - plocate
