# vim: et
---

powerline_shell_theme_file: /usr/share/powerline/config_files/themes/shell/__main__.json

common_packages_platform_specific:
  - mlocate
  - vim
  - dictionaries-common # For dictionary /usr/share/dict/
