# vim: et
---

__common_required_facts:
  - os_family

common_packages:
  - autojump
  - bat
  - fzf
  - git
  - powerline
  - syncthing
  - timeshift
  - tmux

common_graphical_packages:
  - flameshot
  - redshift
