# vim: et
---

powerline_shell_theme_file: /etc/xdg/powerline/themes/shell/__main__.json

common_packages_platform_specific:
  - autojump-fish
  - dnf-plugins-core
  - plocate
  - vim-X11
  - vim-enhanced
  - words # For dictionary /usr/share/dict/
